# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='time_created',
            new_name='created_at',
        ),
    ]
