# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_auto_20170612_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='descrition',
            new_name='description',
        ),
    ]
