# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_time',
            field=models.DateTimeField(null=True),
        ),
    ]
