# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 16:09
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20170614_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='US/Central'),
        ),
    ]
